# Generated by Django 3.1.2 on 2020-12-03 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0005_student_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='course',
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название работы')),
                ('desc', models.CharField(max_length=255, verbose_name='описание')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.course')),
            ],
        ),
        migrations.AddField(
            model_name='mark',
            name='checkpoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentapp.checkpoint'),
        ),
    ]
