# Generated by Django 3.1.2 on 2020-12-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0006_auto_20201203_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
